In [10]:
import numpy as np
import pandas as pd
from pathlib import Path
import hvplot.pandas

In [19]:
# Load the data
file_path2014 = Path('./Resources/2014.csv')
df_2014 = pd.read_csv(file_path2014, skiprows=1)[:-2]

file_path2015 = Path('./Resources/2015.csv')
df_2015 = pd.read_csv(file_path2015, skiprows=1)[:-2]

file_path2016Q1 = Path('./Resources/2016Q1.csv')
df_2016Q1 = pd.read_csv(file_path2016Q1, skiprows=1)[:-2]

file_path2016Q2 = Path('./Resources/2016Q2.csv')
df_2016Q2 = pd.read_csv(file_path2016Q2, skiprows=1)[:-2]

file_path2016Q3 = Path('./Resources/2016Q3.csv')
df_2016Q3 = pd.read_csv(file_path2016Q3, skiprows=1)[:-2]

file_path2016Q4 = Path('./Resources/2016Q4.csv')
df_2016Q4 = pd.read_csv(file_path2016Q4, skiprows=1)[:-2]

/Users/ricky/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0,19,49,59) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/ricky/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0,19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/ricky/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0,19,59) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [22]:
#combined 2014 to 2016 data

df_all=[df_2014,df_2015,df_2016Q1,df_2016Q2,df_2016Q3,df_2016Q4]

raw_data = pd.concat(df_all)
raw_data.describe()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,fico_range_low,fico_range_high,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,1.091131e+06,1.091131e+06,1.091131e+06,1.091131e+06,1.091131e+06,1.091066e+06,1.091131e+06,1.091131e+06,1.091131e+06,...,13368.000000,16593.000000,13368.000000,13368.000000,14904.000000,16593.000000,16593.000000,32378.000000,32378.000000,32378.000000
mean,NaN,1.495881e+04,1.495878e+04,1.495290e+04,4.428673e+02,7.751796e+04,1.879634e+01,3.520109e-01,6.940892e+02,6.980893e+02,...,2.742071,176.088469,2.742071,8.863256,239.819177,6727.954911,510.718046,4702.982847,47.120705,13.280561
std,NaN,8.716084e+03,8.716085e+03,8.713271e+03,2.554981e+02,7.181074e+04,9.360157e+00,9.301704e-01,3.048344e+01,3.048407e+01,...,0.574818,223.956468,0.574818,10.229227,271.909712,5879.856529,1130.371601,3480.004708,6.846875,7.840149
min,NaN,1.000000e+03,1.000000e+03,7.750000e+02,1.401000e+01,0.000000e+00,-1.000000e+00,0.000000e+00,6.600000e+02,6.640000e+02,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,8.000000e+03,8.000000e+03,8.000000e+03,2.581000e+02,4.700000e+04,1.235000e+01,0.000000e+00,6.700000e+02,6.740000e+02,...,2.000000,0.000000,2.000000,0.000000,63.265000,2546.620000,108.880000,2030.000000,45.000000,6.000000
50%,NaN,1.305000e+04,1.305000e+04,1.302500e+04,3.815500e+02,6.500000e+04,1.823000e+01,0.000000e+00,6.850000e+02,6.890000e+02,...,3.000000,74.680000,3.000000,3.000000,153.919440,5310.550000,306.380000,3926.000000,45.000000,14.000000
75%,NaN,2.000000e+04,2.000000e+04,2.000000e+04,5.839050e+02,9.200000e+04,2.480000e+01,0.000000e+00,7.100000e+02,7.140000e+02,...,3.000000,289.500000,3.000000,18.000000,319.214767,9366.160000,517.720000,6500.000000,50.000000,18.000000
max,NaN,4.000000e+04,4.000000e+04,4.000000e+04,1.584900e+03,9.573072e+06,9.990000e+02,3.900000e+01,8.450000e+02,8.500000e+02,...,4.000000,1463.490000,4.000000,113.000000,2717.340000,36344.870000,19281.590000,30000.000000,521.350000,112.000000

In [26]:
raw_data.to_csv('loan_2014to2016.csv')